branches:
  only:
    - master
language: python
python:
  - "3.8"
services:
  - docker

after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:latest
