branches:
  only:
    - master

language: python

python:
  - "3.8"

services:
  - docker

install: skip

before_script:
  - cd synthetic-data-app

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:latest
